### ISSUE TITLE
UT filter with Pytest markers on standard pipeline [s1]

### ISSUE THREAD

**Issue by debrando** [prometeia/promebuilder#13]

**Comment by debrando** [comment]
Recepita la nuova lib ramo "pipeline" di promebuilder su gsf e pytho. Adattato il runner notturlo https://pythoci.prometeia.it/blue/organizations/jenkins/nrt_runner_develop/activity/ per chiamare le due build a parametro "test_markers" vuoto, che implica l'eseguire tutti i test e implicitamente buildare anche per windows.

**Comment by debrando** [comment]
@glaucouri ho aggiunto un [conftest.py](https://github.com/prometeia/gsf/blob/952a58a880ef0b174b8e6c63d2b244edbd0411e8/tests_nr/conftest.py#L3) per automarcare tutta la vecchia "sim_suite" come "slow"; tutto il ramo "from_file" l'ho invece marcato a mano, c'erano solo tre funzioni con fixture. Ti lascio la issue per i test da lancio parametrico.

I test ora utilizzano entrembe le folder grazie alla configurazione in pytest.ini. Segnalo però che in questo c'è ancora la selezione mirata di certi path sotto la test, `tests/utils tests/model tests/backends tests/conda tests/grammars tests/storage tests/test_jupyter.py tests/promlab`, possiamo pensare di buttare il resto se non funziona?

**Comment by glaucouri** [comment]
Il resto l'ho già sistemato e localmente ho la coverage completa usando la discovery di base:
- rimosso i calibratori (tutto codice C) che non usiamo, veramente un peccato, ma ora è solo un inutile peso
- Aggiornato tutti i test della InFame e
- eliminato tutti i test sviluppati nel tempo per i vari engine come MPI, producer/consumer e lacuni test di celery (ma non automatizzati)

Quindi i test sono attivabili tutti in autodiscovery, per le info che ho, rimane scoperto il tema cluster con celery. 
Tema che rimanderei perchè nelle versioni successive di celery hanno aggiunto un bridge con la pytest che mi piacerebbe esplorare.

**Comment by glaucouri** [comment]
Aggiungo una cosa, @debrando  hai capito perchè il mio precedente tentativo di aggiungere il marker a runtime non girava?

**Comment by glaucouri** [comment]
Esteso i test in discovery anche per la gsf.
i test della gsf sono più che raddoppiati
