### ISSUE TITLE
Test automatici tramite Postman per non-programmatori

### ISSUE THREAD

**Issue by loredanaribatto** [prometeia/promebuilder#7]
Configurare ambienti e definire iter di test

**Comment by debrando** [comment]
Per le automazioni, l'idea è la seguente:

1. Posizionare in luogo standard le suite di test test postman da lanciarsi in automatico.
1. Inserire anche le configurazioni environment (senza cablare le password, magari).
1. Utilizzare  [NewMan](https://www.npmjs.com/package/newman) per lanciare riga comando tutte le suite di test trovate.

**Comment by debrando** [comment]
$ newman run pytho-auth-v0.postman_collection.json -e pythobeta.postman_environment.json

    (...)
    ┌─────────────────────────┬───────────────────┬───────────────────┐
    │                         │          executed │            failed │
    ├─────────────────────────┼───────────────────┼───────────────────┤
    │              iterations │                 1 │                 0 │
    ├─────────────────────────┼───────────────────┼───────────────────┤
    │                requests │                 9 │                 0 │
    ├─────────────────────────┼───────────────────┼───────────────────┤
    │            test-scripts │                 9 │                 0 │
    ├─────────────────────────┼───────────────────┼───────────────────┤
    │      prerequest-scripts │                 3 │                 0 │
    ├─────────────────────────┼───────────────────┼───────────────────┤
    │              assertions │                 9 │                 2 │
    ├─────────────────────────┴───────────────────┴───────────────────┤
    │ total run duration: 1064ms                                      │
    ├─────────────────────────────────────────────────────────────────┤
    │ total data received: 2.78KB (approx)                            │
    ├─────────────────────────────────────────────────────────────────┤
    │ average response time: 53ms [min: 26ms, max: 188ms, s.d.: 50ms] │
    └─────────────────────────────────────────────────────────────────┘

    #  failure                   detail

    1.  AssertionError            response is ok
                                expected response to have status code 200 but got 401
                                at assertion:0 in test-script
                                inside "ticket/<ticket>"

    2.  AssertionError            response is ok
                                expected response to have status code 200 but got 500
                                at assertion:0 in test-script
                                inside "search/resource"
